name: tests

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  bot:
    name: check graph loads
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
        with:
          path: cf-graph

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge

      - name: install bot code
        run: |
          mamba install -y -q pygithub requests git pytest

          git config --global user.name regro-cf-autotick-bot
          git config --global user.email 36490558+regro-cf-autotick-bot@users.noreply.github.com
          git config --global pull.rebase false

          conda config --env --set add_pip_as_python_dependency False
          conda info
          conda config --show-sources
          conda list --show-channel-urls

          git clone --depth=1 https://github.com/regro/cf-scripts.git
          pushd cf-scripts
          export GIT_FULL_HASH=$(git rev-parse HEAD)
          mamba create -n run_env --yes --quiet curl python=3.9
          conda activate run_env
          for i in `seq 1 10`; do
            echo $i
            mamba install --quiet --yes --file requirements/run || echo 'mamba install failed!'
          done
          mamba install --quiet --yes --file requirements/run

          python setup.py develop
          popd

          git clone --depth=1 https://github.com/conda-forge/conda-forge-pinning-feedstock.git

      - name: load graph
        run: |
          pushd cf-graph
          conda activate run_env
          pytest -vv test_load_graph.py
          popd
